# Generated by Django 5.0.6 on 2024-06-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelwithfilefield',
            name='folder_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
