# Generated by Django 5.0.6 on 2024-06-20 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_folder_remove_modelwithfilefield_folder_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='storage.folder'),
        ),
    ]
